//! KugelAudio (`kugelaudio/kugelaudio-0-open`): a post-trained fine-tune of
//! Microsoft's VibeVoice architecture — a Qwen2 decoder backbone that
//! autoregressively interleaves text tokens with continuous speech latents,
//! the latter generated by a small diffusion head + DPM-Solver++ sampler
//! and encoded/decoded through causal-conv VAE "tokenizers". See
//! `config.rs` for the full architecture summary and weight-name notes, and
//! `model.rs` for what's wired up so far vs. deferred (the autoregressive
//! `generate()` loop is not yet ported — see that module's doc comment).

pub mod config;
pub mod connector;
pub mod conv_layers;
pub mod decoder;
pub mod diffusion_head;
pub mod dpm_solver;
pub mod model;
pub mod prompt;

pub use config::{KugelAudioConfig, load_config};
pub use model::{KugelAudioGenerationConfig, KugelAudioGenerationOutput, KugelAudioModel};
pub use prompt::{PromptResult, build_prompt};
