//! ONNX model inspection and execution helpers.
//!
//! The public API in this module deliberately hides Candle types.  It is
//! useful for tools which need to verify whether Candle's ONNX evaluator can
//! execute a model without becoming coupled to Candle themselves.

use std::collections::{HashMap, HashSet};
use std::path::Path;

use anyhow::{Context, Result, anyhow, bail};
use candle_core::Result as CandleResult;
use candle_core::{Device, Tensor};
use prost::Message;

/// ONNX protobuf types generated from the vendored ONNX schema.
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
}

/// Candle-backed evaluator maintained by Crane.
#[path = "onnx/eval.rs"]
pub mod eval;

#[path = "onnx/session.rs"]
mod session;

/// Cross-cutting evaluator bookkeeping not tied to any single op (e.g.
/// "If"-branch value capture/eviction), shared by `eval.rs`'s main loop.
#[path = "onnx/utils.rs"]
mod utils;

#[path = "onnx/optimizer/mod.rs"]
mod optimizer;

/// Crane-specific ONNX operators. Keep evaluator dispatch in `eval.rs` so
/// upstream evaluator updates remain straightforward to merge.
#[path = "onnx/ops/mod.rs"]
pub(crate) mod ops;

pub use eval::{dtype, simple_eval};
pub(crate) use optimizer::optimize;
pub use optimizer::{OptimizationReport, SessionOptions};
pub use session::Session;

/// Decodes an ONNX protobuf model from disk.
pub fn read_file<P: AsRef<Path>>(path: P) -> CandleResult<proto::ModelProto> {
    let bytes = std::fs::read(path)?;
    proto::ModelProto::decode(bytes.as_slice()).map_err(candle_core::Error::wrap)
}

use proto::tensor_proto::DataType;

/// Metadata about a graph input or output used by [`probe_onnx_model`].
#[derive(Clone, Debug)]
pub struct OnnxProbeTensorInfo {
    pub name: String,
    pub dtype: String,
    pub shape: Vec<usize>,
}

/// A graph operation reported by [`probe_onnx_model`].
#[derive(Clone, Debug)]
pub struct OnnxProbeOperation {
    pub index: usize,
    pub name: String,
    pub op_type: String,
    pub domain: String,
}

/// The result of successfully loading and executing an ONNX graph on CPU.
#[derive(Clone, Debug)]
pub struct OnnxProbeReport {
    /// Model inputs generated by the probe. Initializers are not listed here.
    pub inputs: Vec<OnnxProbeTensorInfo>,
    pub outputs: Vec<OnnxProbeTensorInfo>,
    pub operations: Vec<OnnxProbeOperation>,
}

/// Loads an ONNX model and executes one CPU forward pass through Candle.
///
/// Inputs are zero-filled tensors. Static dimensions come from the model;
/// symbolic or unknown dimensions use `dynamic_dim`. This validates graph
/// loading and operator support, but cannot prove application-level numerical
/// correctness for arbitrary real inputs.
pub fn probe_onnx_model(path: impl AsRef<Path>, dynamic_dim: usize) -> Result<OnnxProbeReport> {
    if dynamic_dim == 0 {
        bail!("--dynamic-dim must be at least 1");
    }

    let path = path.as_ref();
    if !path.is_file() {
        bail!("ONNX model was not found: {}", path.display());
    }

    let model = read_file(path)
        .with_context(|| format!("could not decode ONNX model {}", path.display()))?;
    let graph = model
        .graph
        .as_ref()
        .ok_or_else(|| anyhow!("ONNX model has no graph"))?;

    let operations = graph
        .node
        .iter()
        .enumerate()
        .map(|(index, node)| OnnxProbeOperation {
            index,
            name: node.name.clone(),
            op_type: node.op_type.clone(),
            domain: node.domain.clone(),
        })
        .collect::<Vec<_>>();
    let unsupported = operations
        .iter()
        .filter(|operation| {
            !operation.domain.is_empty()
                || !CANDLE_SIMPLE_EVAL_OPS.contains(&operation.op_type.as_str())
        })
        .collect::<Vec<_>>();
    if !unsupported.is_empty() {
        let details = unsupported
            .iter()
            .map(|operation| operation_description(operation))
            .collect::<Vec<_>>()
            .join("\n  ");
        bail!(
            "Candle's ONNX evaluator cannot execute this graph because it contains unsupported operation(s):\n  {details}\n\n{}",
            unsupported_operator_solutions()
        );
    }

    let initializer_names = graph
        .initializer
        .iter()
        .map(|initializer| initializer.name.as_str())
        .collect::<HashSet<_>>();
    let mut input_info = Vec::new();
    let mut inputs = HashMap::new();
    for input in graph
        .input
        .iter()
        .filter(|input| !initializer_names.contains(input.name.as_str()))
    {
        let (shape, dtype) = tensor_spec(input, dynamic_dim)?;
        input_info.push(OnnxProbeTensorInfo {
            name: input.name.clone(),
            dtype: format!("{dtype:?}"),
            shape: shape.clone(),
        });
        let tensor = Tensor::zeros(shape, dtype, &Device::Cpu)
            .with_context(|| format!("could not create probe input '{}'", input.name))?;
        inputs.insert(input.name.clone(), tensor);
    }

    let values = simple_eval(&model, inputs).map_err(|error| {
        anyhow!(
            "Candle loaded the model but its CPU forward pass failed: {error:#}\n\n{}",
            forward_failure_solutions()
        )
    })?;
    let outputs = graph
        .output
        .iter()
        .map(|output| {
            let tensor = values.get(&output.name).ok_or_else(|| {
                anyhow!(
                    "Candle completed evaluation but did not return output '{}'",
                    output.name
                )
            })?;
            Ok(OnnxProbeTensorInfo {
                name: output.name.clone(),
                dtype: format!("{:?}", tensor.dtype()),
                shape: tensor.dims().to_vec(),
            })
        })
        .collect::<Result<Vec<_>>>()?;

    Ok(OnnxProbeReport {
        inputs: input_info,
        outputs,
        operations,
    })
}

fn tensor_spec(
    input: &proto::ValueInfoProto,
    dynamic_dim: usize,
) -> Result<(Vec<usize>, candle_core::DType)> {
    let tensor_type = input
        .r#type
        .as_ref()
        .and_then(|value_type| value_type.value.as_ref())
        .and_then(|value| match value {
            proto::type_proto::Value::TensorType(tensor_type) => Some(tensor_type),
            _ => None,
        })
        .ok_or_else(|| {
            anyhow!(
                "input '{}' is not a tensor; Candle's simple ONNX evaluator only accepts tensors",
                input.name
            )
        })?;
    let data_type = DataType::try_from(tensor_type.elem_type).map_err(|_| {
        anyhow!(
            "input '{}' has unknown ONNX element type {}",
            input.name,
            tensor_type.elem_type
        )
    })?;
    let dtype = dtype(data_type).ok_or_else(|| {
        anyhow!(
            "input '{}' has unsupported ONNX element type {data_type:?}",
            input.name
        )
    })?;
    let shape = tensor_type
        .shape
        .as_ref()
        .ok_or_else(|| anyhow!("input '{}' has no tensor shape", input.name))?
        .dim
        .iter()
        .map(|dimension| match &dimension.value {
            Some(proto::tensor_shape_proto::dimension::Value::DimValue(value)) if *value >= 0 => {
                usize::try_from(*value)
                    .map_err(|_| anyhow!("input '{}' has an invalid dimension {value}", input.name))
            },
            _ => Ok(dynamic_dim),
        })
        .collect::<Result<Vec<_>>>()?;
    Ok((shape, dtype))
}

fn operation_description(operation: &OnnxProbeOperation) -> String {
    let name = if operation.name.is_empty() {
        "<unnamed>"
    } else {
        &operation.name
    };
    let domain = if operation.domain.is_empty() {
        "ai.onnx"
    } else {
        &operation.domain
    };
    format!(
        "node #{} '{}' ({}::{})",
        operation.index, name, domain, operation.op_type
    )
}

fn unsupported_operator_solutions() -> &'static str {
    "Possible next steps: export with a lower/supported ONNX opset, simplify the graph with onnxsim, replace the listed operation before export, or use ONNX Runtime for this model. Crane support can also be added by implementing the operator in crane_core::onnx."
}

fn forward_failure_solutions() -> &'static str {
    "Possible next steps: check the generated zero-input shapes (especially symbolic dimensions), retry with --dynamic-dim matching your real batch/sequence size, or simplify/export the model with a compatible ONNX opset. If the error names an operator, use ONNX Runtime or add that operator to crane_core::onnx."
}

const CANDLE_SIMPLE_EVAL_OPS: &[&str] = &[
    "Abs",
    "Add",
    "And",
    "ArgMax",
    "ArgMin",
    "Atan",
    "Atan2",
    "AveragePool",
    "BatchNormalization",
    "Cast",
    "Ceil",
    "Clip",
    "Concat",
    "Constant",
    "ConstantOfShape",
    "Conv",
    "ConvTranspose",
    "Cos",
    "CumSum",
    "Div",
    "Dropout",
    "Equal",
    "Erf",
    "Exp",
    "Expand",
    "Flatten",
    "Floor",
    "Gather",
    "GatherElements",
    "Gelu",
    "Gemm",
    "GlobalAveragePool",
    "Greater",
    "GreaterOrEqual",
    "HardSigmoid",
    "HardSwish",
    "Identity",
    "If",
    "LSTM",
    "LeakyRelu",
    "Less",
    "LessOrEqual",
    "Log",
    "LogSoftmax",
    "MatMul",
    "MaxPool",
    "Min",
    "Mul",
    "Neg",
    "NonZero",
    "Not",
    "OneHot",
    "Or",
    "PRelu",
    "Pad",
    "Pow",
    "RNN",
    "Range",
    "ReduceL2",
    "ReduceMax",
    "ReduceMean",
    "ReduceMin",
    "ReduceSum",
    "Relu",
    "Reshape",
    "Resize",
    "STFT",
    "ScatterND",
    "Selu",
    "Shape",
    "Sigmoid",
    "Sign",
    "Sin",
    "Size",
    "Slice",
    "Softmax",
    "Split",
    "Sqrt",
    "Squeeze",
    "Sub",
    "Tanh",
    "Tile",
    "Transpose",
    "Trilu",
    "Unsqueeze",
    "Where",
    "Xor",
];
